name: connection_repository
description: Repository to manage the connection state.
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  gyver_lamp_client:
    path: ../gyver_lamp_client
  meta: ^1.17.0

dev_dependencies:
  fake_async: ^1.3.3 
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
