name: gyver_lamp
description: Gyver Lamp Application.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  connection_repository:
    path: packages/connection_repository
  control_repository:
    path: packages/control_repository
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  gyver_lamp_client:
    path: packages/gyver_lamp_client
  gyver_lamp_effects:
    path: packages/gyver_lamp_effects
  gyver_lamp_icons:
    path: packages/gyver_lamp_icons
  gyver_lamp_ui:
    path: packages/gyver_lamp_ui
  intl: ^0.20.2
  logging: ^1.3.0
  provider: ^6.1.5+1
  rive: ^0.11.17
  settings_controller:
    path: packages/settings_controller
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mockingjay: ^2.1.0
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

workspace:
  - packages/connection_repository/
  - packages/control_repository/
  - packages/gyver_lamp_client/
  - packages/gyver_lamp_effects/
  - packages/gyver_lamp_icons/
  - packages/gyver_lamp_ui/
  - packages/settings_controller/

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/switch.riv
