name: gyver_lamp_client
description: Client to communicate with the Gyver Lamp.
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  meta: ^1.17.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
