name: gyver_lamp_icons
description: Icons set for Gyver Lamp.
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  fonts:
    - family: GyverLampIcons
      fonts:
        - asset: assets/fonts/GyverLampIcons.ttf
