name: gyver_lamp_ui
description: UI Toolkit for Gyver Lamp
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  gyver_lamp_icons:
    path: ../gyver_lamp_icons
  meta: ^1.17.0
  tactile_feedback:
    git:
      url: https://github.com/ksokolovskyi/tactile_feedback
      ref: 75408aa957c32234ff3624c2d861a1d00e764d4c

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockingjay: ^2.1.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
