name: gyver_lamp_effects
description: Gyver Lamp Effects
version: 1.0.0
publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  gyver_lamp_icons:
    path: ../gyver_lamp_icons
  gyver_lamp_ui:
    path: ../gyver_lamp_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
